import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireAdmin } from "@/lib/auth";
import { Globe, Key, FileText } from "lucide-react";

export default async function AdminSettingsPage() {
  try { await requireAdmin(); } catch { return null; }

  return (
    <div className="p-6 space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Network Settings</h1>
        <p className="text-gray-500 text-sm mt-1">YieldProsper configuration</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Key size={16} />Demand Integration</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          {[
            ["Prebid Publisher ID (pId)", "25cv68n329154k1909176mw4"],
            ["Display CId", "6a0f24939f9529b6eec283e7"],
            ["Video CId", "6a0f249fb01f8a0cb9562731"],
            ["API Key", "pub_live_3a66bd0…(set in .env)"],
          ].map(([k, v]) => (
            <div key={k} className="flex justify-between">
              <span className="text-gray-500">{k}</span>
              <code className="text-xs text-gray-700 font-mono">{v}</code>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Globe size={16} />Sellers.json</CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-2">
          <p className="text-gray-500">Your network sellers.json is publicly available at:</p>
          <a href="/api/sellers.json" target="_blank" rel="noopener noreferrer"
            className="text-indigo-600 hover:underline font-mono text-xs">
            /api/sellers.json
          </a>
          <p className="text-gray-400 text-xs mt-2">
            This file is automatically generated from all active publisher accounts and cached for 1 hour.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><FileText size={16} />ads.txt</CardTitle>
        </CardHeader>
        <CardContent className="text-sm">
          <p className="text-gray-500 mb-2">Per-domain ads.txt files are served at:</p>
          <code className="text-xs text-gray-700 font-mono bg-gray-50 px-2 py-1 rounded">
            /api/ads-txt/&#123;domain&#125;
          </code>
          <p className="text-gray-400 text-xs mt-3">
            Contains full supply chain entries plus any publisher-specific custom entries.
            Publishers can view their ads.txt URL in the Settings page.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
